[2025-03-11T17:57:06.963+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-11T17:57:07.207+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_dag.upload_to_minio manual__2025-03-11T17:55:59.875329+00:00 [queued]>
[2025-03-11T17:57:07.232+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_dag.upload_to_minio manual__2025-03-11T17:55:59.875329+00:00 [queued]>
[2025-03-11T17:57:07.236+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-11T17:57:07.300+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_to_minio> on 2025-03-11 17:55:59.875329+00:00
[2025-03-11T17:57:07.353+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=651) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-11T17:57:07.357+0000] {standard_task_runner.py:72} INFO - Started process 653 to run task
[2025-03-11T17:57:07.357+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'minio_dag', 'upload_to_minio', 'manual__2025-03-11T17:55:59.875329+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpnyruclsx']
[2025-03-11T17:57:07.359+0000] {standard_task_runner.py:105} INFO - Job 34: Subtask upload_to_minio
[2025-03-11T17:57:07.457+0000] {task_command.py:467} INFO - Running <TaskInstance: minio_dag.upload_to_minio manual__2025-03-11T17:55:59.875329+00:00 [running]> on host 864bdb0a156f
[2025-03-11T17:57:07.581+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_dag' AIRFLOW_CTX_TASK_ID='upload_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T17:55:59.875329+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T17:55:59.875329+00:00'
[2025-03-11T17:57:07.583+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-11T17:57:07.584+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-11T17:57:07.584+0000] {logging_mixin.py:190} INFO - Current task name:upload_to_minio state:running start_date:2025-03-11 17:57:07.209205+00:00
[2025-03-11T17:57:07.585+0000] {logging_mixin.py:190} INFO - Dag name:minio_dag and current dag run status:running
[2025-03-11T17:57:07.586+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-11T17:57:07.587+0000] {logging_mixin.py:190} INFO - Début de l'upload vers MinIO à 2025-03-11 17:57:07.587275
[2025-03-11T17:57:07.588+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 21, in upload_to_minio
    os.makedirs(os.path.dirname(LOCAL_PATH), exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [Errno 2] No such file or directory: ''
[2025-03-11T17:57:07.605+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-11T17:57:07.606+0000] {logging_mixin.py:190} INFO - Task start:2025-03-11 17:57:07.209205+00:00 end:2025-03-11 17:57:07.605062+00:00 duration:0.395857
[2025-03-11T17:57:07.607+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): upload_to_minio> dag:<DAG: minio_dag> dagrun:<DagRun minio_dag @ 2025-03-11 17:55:59.875329+00:00: manual__2025-03-11T17:55:59.875329+00:00, state:running, queued_at: 2025-03-11 17:55:59.896180+00:00. externally triggered: True>
[2025-03-11T17:57:07.607+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: ''
[2025-03-11T17:57:07.608+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=minio_dag, task_id=upload_to_minio, run_id=manual__2025-03-11T17:55:59.875329+00:00, execution_date=20250311T175559, start_date=20250311T175707, end_date=20250311T175707
[2025-03-11T17:57:07.646+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-11T17:57:07.647+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 34 for task upload_to_minio ([Errno 2] No such file or directory: ''; 653)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 21, in upload_to_minio
    os.makedirs(os.path.dirname(LOCAL_PATH), exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [Errno 2] No such file or directory: ''
[2025-03-11T17:57:07.699+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-11T17:57:07.743+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T17:57:07.750+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
