[2025-03-11T18:09:44.381+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-11T18:09:44.647+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_dag.list_objects_in_bucket manual__2025-03-11T18:09:31.184881+00:00 [queued]>
[2025-03-11T18:09:44.674+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_dag.list_objects_in_bucket manual__2025-03-11T18:09:31.184881+00:00 [queued]>
[2025-03-11T18:09:44.678+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-11T18:09:44.713+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): list_objects_in_bucket> on 2025-03-11 18:09:31.184881+00:00
[2025-03-11T18:09:44.728+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=826) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-11T18:09:44.733+0000] {standard_task_runner.py:72} INFO - Started process 828 to run task
[2025-03-11T18:09:44.733+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'minio_dag', 'list_objects_in_bucket', 'manual__2025-03-11T18:09:31.184881+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmprssaa5ca']
[2025-03-11T18:09:44.736+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask list_objects_in_bucket
[2025-03-11T18:09:44.855+0000] {task_command.py:467} INFO - Running <TaskInstance: minio_dag.list_objects_in_bucket manual__2025-03-11T18:09:31.184881+00:00 [running]> on host 864bdb0a156f
[2025-03-11T18:09:45.088+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_dag' AIRFLOW_CTX_TASK_ID='list_objects_in_bucket' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T18:09:31.184881+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T18:09:31.184881+00:00'
[2025-03-11T18:09:45.090+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-11T18:09:45.091+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-11T18:09:45.092+0000] {logging_mixin.py:190} INFO - Current task name:list_objects_in_bucket state:running start_date:2025-03-11 18:09:44.648538+00:00
[2025-03-11T18:09:45.094+0000] {logging_mixin.py:190} INFO - Dag name:minio_dag and current dag run status:running
[2025-03-11T18:09:45.096+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-11T18:09:54.015+0000] {logging_mixin.py:190} INFO - ðŸš¨ Erreur lors de la liste des objets : Could not connect to the endpoint URL: "http://localhost:9001/test?list-type=2&encoding-type=url"
[2025-03-11T18:09:54.016+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-11T18:09:54.030+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-11T18:09:54.031+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=minio_dag, task_id=list_objects_in_bucket, run_id=manual__2025-03-11T18:09:31.184881+00:00, execution_date=20250311T180931, start_date=20250311T180944, end_date=20250311T180954
[2025-03-11T18:09:54.070+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-11T18:09:54.071+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-11T18:09:54.072+0000] {logging_mixin.py:190} INFO - Dag name:minio_dag queued_at:2025-03-11 18:09:31.206430+00:00
[2025-03-11T18:09:54.072+0000] {logging_mixin.py:190} INFO - Task hostname:864bdb0a156f operator:PythonOperator
[2025-03-11T18:09:54.088+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-11T18:09:54.122+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-11T18:09:54.125+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
